// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/api/grpc/proto/device.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_api_grpc_proto_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_device_proto_rawDescGZIP(), []int{0}
}

type DeviceInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HardwareVersion string                 `protobuf:"bytes,2,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,3,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,4,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Checksum        string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_internal_api_grpc_proto_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_proto_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_proto_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *DeviceInfo) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *DeviceInfo) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *DeviceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceInfo) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

var File_internal_api_grpc_proto_device_proto protoreflect.FileDescriptor

const file_internal_api_grpc_proto_device_proto_rawDesc = "" +
	"\n" +
	"$internal/api/grpc/proto/device.proto\x12\x06device\"\a\n" +
	"\x05Empty\"\xd1\x01\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10hardware_version\x18\x02 \x01(\tR\x0fhardwareVersion\x12)\n" +
	"\x10software_version\x18\x03 \x01(\tR\x0fsoftwareVersion\x12)\n" +
	"\x10firmware_version\x18\x04 \x01(\tR\x0ffirmwareVersion\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum2=\n" +
	"\rDeviceService\x12,\n" +
	"\aGetInfo\x12\r.device.Empty\x1a\x12.device.DeviceInfoB\x1fZ\x1dinternal/api/grpc/proto;protob\x06proto3"

var (
	file_internal_api_grpc_proto_device_proto_rawDescOnce sync.Once
	file_internal_api_grpc_proto_device_proto_rawDescData []byte
)

func file_internal_api_grpc_proto_device_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_proto_device_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_proto_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_grpc_proto_device_proto_rawDesc), len(file_internal_api_grpc_proto_device_proto_rawDesc)))
	})
	return file_internal_api_grpc_proto_device_proto_rawDescData
}

var file_internal_api_grpc_proto_device_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_grpc_proto_device_proto_goTypes = []any{
	(*Empty)(nil),      // 0: device.Empty
	(*DeviceInfo)(nil), // 1: device.DeviceInfo
}
var file_internal_api_grpc_proto_device_proto_depIdxs = []int32{
	0, // 0: device.DeviceService.GetInfo:input_type -> device.Empty
	1, // 1: device.DeviceService.GetInfo:output_type -> device.DeviceInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_proto_device_proto_init() }
func file_internal_api_grpc_proto_device_proto_init() {
	if File_internal_api_grpc_proto_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_grpc_proto_device_proto_rawDesc), len(file_internal_api_grpc_proto_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_grpc_proto_device_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_proto_device_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_proto_device_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_proto_device_proto = out.File
	file_internal_api_grpc_proto_device_proto_goTypes = nil
	file_internal_api_grpc_proto_device_proto_depIdxs = nil
}
